# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: eec401bc23795a13934e87c09e40e4904fd933e7557cfcdff2fc467f1f719ea8868a9ea1582bb74aba9293a149a18ac3a7463bf5406bdcd2954927279d837ce0

test:
  secret_key_base: 91c7a42d6cbd78d00182b28d6a19d79b4f27c57399d88e20a575fc05296d09ecd408da8c676af27b2454a7761e6d923a344e2028aae2a16b383e2524412caff0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
