
School.create(name: "London Primary")
School.create(name: "London Grammar")
School.create(name: "London University")
School.create(name: "Manchester Primary")
School.create(name: "Manchester Grammar")
School.create(name: "Manchester University")
School.create(name: "Edingburgh Primary")
School.create(name: "Edingburgh Grammar")
School.create(name: "Edingburgh University")
